var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(k,g,y){k!=Array.prototype&&k!=Object.prototype&&(k[g]=y.value)};$jscomp.getGlobal=function(k){return"undefined"!=typeof window&&window===k?k:"undefined"!=typeof global&&null!=global?global:k};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.polyfill=function(k,g,y,t){if(g){y=$jscomp.global;k=k.split(".");for(t=0;t<k.length-1;t++){var p=k[t];p in y||(y[p]={});y=y[p]}k=k[k.length-1];t=y[k];g=g(t);g!=t&&null!=g&&$jscomp.defineProperty(y,k,{configurable:!0,writable:!0,value:g})}};$jscomp.polyfill("Math.imul",function(k){return k?k:function(g,k){g=Number(g);k=Number(k);var t=g&65535,p=k&65535;return t*p+((g>>>16&65535)*p+t*(k>>>16&65535)<<16>>>0)|0}},"es6","es3");$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.Symbol=function(){var k=0;return function(g){return $jscomp.SYMBOL_PREFIX+(g||"")+k++}}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var k=$jscomp.global.Symbol.iterator;k||(k=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[k]&&$jscomp.defineProperty(Array.prototype,k,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};
$jscomp.initSymbolAsyncIterator=function(){$jscomp.initSymbol();var k=$jscomp.global.Symbol.asyncIterator;k||(k=$jscomp.global.Symbol.asyncIterator=$jscomp.global.Symbol("asyncIterator"));$jscomp.initSymbolAsyncIterator=function(){}};$jscomp.arrayIterator=function(k){var g=0;return $jscomp.iteratorPrototype(function(){return g<k.length?{done:!1,value:k[g++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(k){$jscomp.initSymbolIterator();k={next:k};k[$jscomp.global.Symbol.iterator]=function(){return this};return k};$jscomp.iteratorFromArray=function(k,g){$jscomp.initSymbolIterator();k instanceof String&&(k+="");var y=0,t={next:function(){if(y<k.length){var p=y++;return{value:g(p,k[p]),done:!1}}t.next=function(){return{done:!0,value:void 0}};return t.next()}};t[Symbol.iterator]=function(){return t};return t};
$jscomp.polyfill("Array.prototype.keys",function(k){return k?k:function(){return $jscomp.iteratorFromArray(this,function(g){return g})}},"es6","es3");(function(k,g,y,t){y=k.createElement(g);y.async=1;y.src="//"+(location.host||"localhost").split(":")[0]+":35729/livereload.js?snipver=1";t=k.getElementsByTagName(g)[0];t.parentNode.insertBefore(y,t)})(document,"script");
var starter=function(k){function g(a,b){b.tag=a;return b}function y(a,b,c){for(var d=Array(c),e=0;e<c;)d[e]=a[b],e=e+1|0,b=b+1|0;return d}function t(a,b){if(0>b||b>=a.length)throw[F,"index out of bounds"];return a[b]}function p(a,b){for(;;){var c=b,d=(b=a.length)?b:1;if(b=d-c.length|0)if(0>b)b=y(c,d,-b|0),a=a.apply(null,y(c,0,d));else return function(a,b){return function(c){return p(a,b.concat([c]))}}(a,c);else return a.apply(null,c)}}function ob(a,b,c){if(7<c||0>c)return p(a,[b]);switch(c){case 0:case 1:return a(b);
case 2:return function(c){return a(b,c)};case 3:return function(c,e){return a(b,c,e)};case 4:return function(c,e,f){return a(b,c,e,f)};case 5:return function(c,e,f,h){return a(b,c,e,f,h)};case 6:return function(c,e,f,h,r){return a(b,c,e,f,h,r)};case 7:return function(c,e,f,h,r,n){return a(b,c,e,f,h,r,n)}}}function m(a,b){var c=a.length;return 1===c?a(b):ob(a,b,c)}function pb(a,b,c,d){if(7<d||0>d)return p(a,[b,c]);switch(d){case 0:case 1:return p(a(b),[c]);case 2:return a(b,c);case 3:return function(d){return a(b,
c,d)};case 4:return function(d,f){return a(b,c,d,f)};case 5:return function(d,f,h){return a(b,c,d,f,h)};case 6:return function(d,f,h,r){return a(b,c,d,f,h,r)};case 7:return function(d,f,h,r,n){return a(b,c,d,f,h,r,n)}}}function A(a,b,c){var d=a.length;return 2===d?a(b,c):pb(a,b,c,d)}function qb(a,b,c,d,e){var f=0;if(7<e||0>e)return p(a,[b,c,d]);switch(e){case 0:case 1:f=1;break;case 2:return p(a(b,c),[d]);case 3:return a(b,c,d);case 4:return function(e){return a(b,c,d,e)};case 5:return function(e,
f){return a(b,c,d,e,f)};case 6:return function(e,f,n){return a(b,c,d,e,f,n)};case 7:return function(e,f,n,l){return a(b,c,d,e,f,n,l)}}if(1===f)return p(a(b),[c,d])}function Y(a,b,c,d){var e=a.length;return 3===e?a(b,c,d):qb(a,b,c,d,e)}function rb(a,b,c,d,e,f){var h=0;if(7<f||0>f)return p(a,[b,c,d,e]);switch(f){case 0:case 1:h=1;break;case 2:return p(a(b,c),[d,e]);case 3:return p(a(b,c,d),[e]);case 4:return a(b,c,d,e);case 5:return function(f){return a(b,c,d,e,f)};case 6:return function(f,h){return a(b,
c,d,e,f,h)};case 7:return function(f,h,l){return a(b,c,d,e,f,h,l)}}if(1===h)return p(a(b),[c,d,e])}function sb(a,b,c,d,e,f,h){var r=0;if(7<h||0>h)return p(a,[b,c,d,e,f]);switch(h){case 0:case 1:r=1;break;case 2:return p(a(b,c),[d,e,f]);case 3:return p(a(b,c,d),[e,f]);case 4:return p(a(b,c,d,e),[f]);case 5:return a(b,c,d,e,f);case 6:return function(h){return a(b,c,d,e,f,h)};case 7:return function(h,l){return a(b,c,d,e,f,h,l)}}if(1===r)return p(a(b),[c,d,e,f])}function tb(a,b,c,d,e,f,h,r){var n=0;if(7<
r||0>r)return p(a,[b,c,d,e,f,h]);switch(r){case 0:case 1:n=1;break;case 2:return p(a(b,c),[d,e,f,h]);case 3:return p(a(b,c,d),[e,f,h]);case 4:return p(a(b,c,d,e),[f,h]);case 5:return p(a(b,c,d,e,f),[h]);case 6:return a(b,c,d,e,f,h);case 7:return function(l){return a(b,c,d,e,f,h,l)}}if(1===n)return p(a(b),[c,d,e,f,h])}function oa(a,b){for(;;){var c=b,d=a;if(d===c)return 1;var e=typeof d;if("string"===e||"number"===e||"boolean"===e||"undefined"===e||null===d)return 0;var f=typeof c;if("function"===
e||"function"===f)throw[F,"equal: functional value"];if("number"===f||"undefined"===f||null===c)return 0;e=d.tag|0;f=c.tag|0;if(250===e)a=d[0];else if(250===f)b=c[0];else{if(248===e)return+(d[1]===c[1]);if(251===e)throw[F,"equal: abstract value"];if(e!==f)return 0;a=d.length|0;if(a===(c.length|0))for(b=0;;){if(b===a)return 1;if(oa(d[b],c[b]))b=b+1|0;else return 0}else return 0}}}function ub(a){if(0>a)throw[F,"String.create"];return Array(a)}function N(a,b){return a===b?0:a<b?-1:1}function pa(a,b,
c,d,e){if(0<e){var f=a.length-b|0;if(e<=f)for(f=0,e=e-1|0;f<=e;++f)c[d+f|0]=a.charCodeAt(b+f|0);else{for(var h=0,r=f-1|0;h<=r;++h)c[d+h|0]=a.charCodeAt(b+h|0);a=f;for(b=e-1|0;a<=b;++a)c[d+a|0]=0}}return 0}function vb(a){var b=a.length,c="",d=b;if(4096>=b&&b===a.length)return String.fromCharCode.apply(null,a);for(b=0;0<d;){var e=1024>d?d:1024,f=Array(e),h=a,r=b,n=f,l=e;if(0<l)if(h===n)if(0>r)for(n=(h.length-0|0)-1|0,l=l-1|0,n=n>l?l:n;0<=n;--n)h[0+n|0]=h[r+n|0];else{if(0<r)for(n=(h.length-r|0)-1|0,
l=l-1|0,n=n>l?l:n,l=0;l<=n;++l)h[0+l|0]=h[r+l|0]}else{var g=h.length-r|0;if(l<=g)for(g=0,l=l-1|0;g<=l;++g)n[0+g|0]=h[r+g|0];else{for(var m=0,k=g-1|0;m<=k;++m)n[0+m|0]=h[r+m|0];h=g;for(r=l-1|0;h<=r;++h)n[0+h|0]=0}}c+=String.fromCharCode.apply(null,f);d=d-e|0;b=b+e|0}return c}function Z(a){qa[0]+=1;a=[a,qa[0]];a.tag=248;return a}function Ha(a,b){for(;;)if(a)b=[a[0],b],a=a[1];else return b}function O(a,b){return b?[m(a,b[0]),O(a,b[1])]:0}function U(a,b){for(;;)if(b)m(a,b[0]),b=b[1];else return 0}function aa(a,
b,c){for(;;){var d=c;if(d)c=d[1],b=A(a,b,d[0]);else return b}}function Ia(a,b,c){return b?A(a,b[0],Ia(a,b[1],c)):c}function wb(a,b,c,d){for(;;){var e=d,f=c;if(f)if(e)d=e[1],c=f[1],b=Y(a,b,f[0],e[0]);else throw[F,"List.fold_left2"];else{if(e)throw[F,"List.fold_left2"];return b}}}function J(a,b){if(b){var c=b[0],d=[0],e=[0];U(function(a){d[0]=d[0]+1|0;e[0]=e[0]+a.length|0;return 0},b);var f=ub(e[0]+xb(a.length,d[0]-1|0)|0);pa(c,0,f,0,c.length);var h=[c.length];U(function(b){pa(a,0,f,h[0],a.length);
h[0]=h[0]+a.length|0;pa(b,0,f,h[0],b.length);h[0]=h[0]+b.length|0;return 0},b[1]);return vb(f)}return""}function ba(a,b,c,d){b=b?b[0]:0;var e=a.style;if(void 0!==e.setProperty)return e.setProperty(c,d,b?"important":null);a.style[c]=d;return 0}function Ja(a,b,c,d){return""===b?a.setAttribute(c,d):a.setAttributeNS(b,c,d)}function yb(a,b,c){return""===b?a.removeAttribute(c):a.removeAttributeNS(b,c)}function Ka(a,b){return""===a?document.createElement(b):document.createElementNS(a,b)}function zb(a,b,
c){return g(3,[a,g(0,[b,c]),[0]])}function ra(a){for(;;){var b=a;switch(b.tag|0){case 0:return"\x3c!-- "+(b[0]+" --\x3e");case 1:return b[0];case 2:a=b[1];var c=b[0];return J("",["<",[c,[""===c?"":":",[a,[J("",O(function(a){if("number"===typeof a)return"";switch(a.tag|0){case 0:return J("",[" ",[a[0],['="',[a[1],['"',0]]]]]);case 1:return J("",[" ",[a[1],['="',[a[2],['"',0]]]]]);case 2:return J("",[" data-",[a[0],['="',[a[1],['"',0]]]]]);case 3:return"";case 4:return J("",[' style="',[J(";",O(function(a){return J("",
[a[0],[":",[a[1],[";",0]]]])},a[0])),['"',0]]])}},b[4])),[">",[J("",O(ra,b[5])),["</",[a,[">",0]]]]]]]]]]);case 3:a=m(b[1],0);continue;case 4:a=b[1]}}}function Ab(a,b){return function(c){return(c=m(b[0],c))?m(a[0][0],c[0]):0}}function La(a){if(a.tag){var b=a[0];return function(){return[b]}}return a[1]}function sa(a,b,c,d){d=[La(d)];a=Ab(a,d);b.addEventListener(c,a,0);return[[a,d]]}function Ma(a,b,c){c&&a.removeEventListener(b,c[0][0],0);return 0}function Bb(a,b,c,d){if("number"===typeof d)return 0;
switch(d.tag|0){case 0:return b[d[0]]=d[1],0;case 1:return Ja(b,d[0],d[1],d[2]);case 2:throw console.log(["TODO:  Add Data Unhandled",d[0],d[1]]),[x,"TODO:  Add Data Unhandled"];case 3:return d[2][0]=sa(a,b,d[0],d[1]),0;case 4:return aa(function(a,c){return ba(b,0,c[0],c[1])},0,d[0])}}function Cb(a,b,c,d){if("number"===typeof d)return 0;switch(d.tag|0){case 0:return b[d[0]]=void 0,0;case 1:return yb(b,d[0],d[1]);case 2:throw console.log(["TODO:  Remove Data Unhandled",d[0],d[1]]),[x,"TODO:  Remove Data Unhandled"];
case 3:return a=d[2],a[0]=Ma(b,d[0],a[0]),0;case 4:return aa(function(a,c){return ba(b,0,c[0],null)},0,d[0])}}function ha(a,b,c,d,e){if("number"===typeof e)throw[x,"This should never be called as all entries through NoProp are gated."];switch(e.tag|0){case 0:return b[e[0]]=e[1],0;case 1:return Ja(b,e[0],e[1],e[2]);case 2:throw console.log(["TODO:  Mutate Data Unhandled",e[0],e[1]]),[x,"TODO:  Mutate Data Unhandled"];case 3:throw[x,"This will never be called because it is gated"];case 4:if("number"===
typeof d)throw[x,"Passed a non-Style to a new Style as a Mutations while the old Style is not actually a style!"];if(4===d.tag)return wb(function(a,c,d){a=d[1];d=d[0];var e=c[0];if(e===d)return c[1]===a?0:ba(b,0,d,a);ba(b,0,e,null);return ba(b,0,d,a)},0,d[0],e[0]);throw[x,"Passed a non-Style to a new Style as a Mutations while the old Style is not actually a style!"];}}function ta(a,b,c,d){a:for(var e=0,f=c,h=d;;){d=h;c=f;var g=e;if(c){var n=c[0],l=0;if(d)if("number"===typeof n)if("number"===typeof d[0]){h=
d[1];f=c[1];e=g+1|0;continue}else l=1;else switch(n.tag|0){case 0:l=d[0];if("number"===typeof l)l=1;else if(l.tag)l=1;else{n[0]===l[0]&&n[1]===l[1]||ha(a,b,g,n,l);h=d[1];f=c[1];e=g+1|0;continue}break;case 1:l=d[0];if("number"===typeof l)l=1;else if(1===l.tag){n[0]===l[0]&&n[1]===l[1]&&n[2]===l[2]||ha(a,b,g,n,l);h=d[1];f=c[1];e=g+1|0;continue}else l=1;break;case 2:l=d[0];if("number"===typeof l)l=1;else if(2===l.tag){n[0]===l[0]&&n[1]===l[1]||ha(a,b,g,n,l);h=d[1];f=c[1];e=g+1|0;continue}else l=1;break;
case 3:l=d[0];if("number"===typeof l)l=1;else if(3===l.tag){f=a;h=b;var m=n[0],k=l[0],w=n[1];e=l[1];var z=n[2];l=l[2];(n=z[0])?m===k?(l[0]=z[0],l=w,f=e,(f.tag?l.tag&&oa(f[0],l[0]):!l.tag&&f[0]===l[0])||(e=La(e),n[0][1][0]=e)):(z[0]=Ma(h,m,z[0]),l[0]=sa(f,h,k,e)):l[0]=sa(f,h,k,e);h=d[1];f=c[1];e=g+1|0;continue}else l=1;break;case 4:if(l=d[0],"number"===typeof l)l=1;else if(4===l.tag){oa(n[0],l[0])||ha(a,b,g,n,l);h=d[1];f=c[1];e=g+1|0;continue}else l=1}else{a=0;break a}1===l&&(e=a,l=b,f=g,h=d[0],Cb(e,
l,f,n),Bb(e,l,f,h),h=d[1],f=c[1],e=g+1|0)}else{a=d?0:1;break a}}return a}function Na(a,b,c,d,e){if(2===e.tag){var f=e[4];c=t(c,d);d=Ka(e[0],e[1]);if(0!==ta(a,d,O(function(){return 0},f),f))return ca(a,d,d.childNodes,0,0,e[5]),b.insertBefore(d,c),b.removeChild(c),0;throw[ua,["/home/samuli/omat/dev/ocaml/little-search/node_modules/bucklescript-tea/src/vdom.ml",319,30]];}throw[x,"Node replacement should never be passed anything but a node itself"];}function ia(a,b){for(;;){var c=b,d=a;switch(c.tag|0){case 0:return document.createComment(c[0]);
case 1:return document.createTextNode(c[0]);case 2:a=c[4];b=Ka(c[0],c[1]);if(0!==ta(d,b,O(function(){return 0},a),a))return ca(d,b,b.childNodes,0,0,c[5]),b;throw[ua,["/home/samuli/omat/dev/ocaml/little-search/node_modules/bucklescript-tea/src/vdom.ml",333,30]];case 3:d=m(c[1],0);b=c[2][0]=d;continue;case 4:b=c[1],a=m(c[0],d)}}}function Oa(a,b,c,d,e,f){if(2===e.tag&&2===f.tag){if(e[3]!==f[3]||e[1]!==f[1])return Na(a,b,c,d,f);var h=t(c,d),g=h.childNodes;ta(a,h,e[4],f[4])||(console.log("VDom:  Failed swapping properties because the property list length changed, use `noProp` to swap properties instead, not by altering the list structure.  This is a massive inefficiency until this issue is resolved."),
Na(a,b,c,d,f));return ca(a,h,g,0,e[5],f[5])}throw[x,"Non-node passed to patchVNodesOnElems_MutateNode"];}function ca(a,b,c,d,e,f){for(;;){var h=f,g=e,n=d;if(g){var l=g[0],q=0;switch(l.tag|0){case 0:if(h)if(q=h[0],q.tag)q=1;else if(l[0]===q[0]){f=h[1];e=g[1];d=n+1|0;continue}else q=1;else q=1;break;case 1:if(h)if(q=h[0],1===q.tag){e=q[0];l[0]!==e&&(t(c,n).nodeValue=e);f=h[1];e=g[1];d=n+1|0;continue}else q=1;else q=1;break;case 2:if(h){var k=h[0];if(2===k.tag){var w=h[1],z=k[2],p=k[1],C=k[0],v=g[1],
D=l[2],R=l[1],V=l[0];if(D===z&&""!==D){f=w;e=v;d=n+1|0;continue}else if(""===D||""===z){Oa(a,b,c,n,l,k);f=w;e=v;d=n+1|0;continue}else{var K=0,S=0;if(v){var T=v[0];if(2===T.tag){var B=v[1],u=T[2],y=T[1];T=T[0];if(w){var x=w[0];if(2===x.tag)if(T===C&&y===p&&u===z&&V===x[0]&&R===x[1]&&D===x[2]){h=t(c,n);e=t(c,n+1|0);b.removeChild(e);b.insertBefore(e,h);f=w[1];e=B;d=n+2|0;continue}else x=4;else x=4}else x=4;if(4===x)if(T===C&&y===p&&u===z){h=t(c,n);b.removeChild(h);f=w;e=B;d=n+1|0;continue}else S=3}else S=
3}else S=3;if(3===S)if(w)if(B=w[0],2===B.tag)if(V===B[0]&&R===B[1]&&D===B[2]){h=t(c,n);d=ia(a,k);b.insertBefore(d,h);f=w;d=n+1|0;continue}else K=2;else K=2;else K=2;if(2===K){Oa(a,b,c,n,l,k);f=w;e=v;d=n+1|0;continue}}}else q=1}else q=1;break;case 3:if(h)if(v=h[0],3===v.tag)if(w=h[1],B=v[2],k=v[1],p=v[0],v=g[1],R=l[2],V=l[0],V===p){B[0]=R[0];f=w;e=v;d=n+1|0;continue}else{K=C=0;if(v)if(z=v[0],3===z.tag){D=v[1];S=z[0];if(w)if(u=w[0],3===u.tag)if(S===p&&V===u[0]){h=t(c,n);e=t(c,n+1|0);b.removeChild(e);
b.insertBefore(e,h);f=w[1];e=D;d=n+2|0;continue}else u=4;else u=4;else u=4;if(4===u)if(S===p){h=t(c,n);b.removeChild(h);B[0]=z[2][0];f=w;e=D;d=n+1|0;continue}else K=3}else K=3;else K=3;if(3===K)if(w)if(D=w[0],3===D.tag)if(D[0]===V){h=t(c,n);d=m(k,0);B[0]=d;d=ia(a,d);b.insertBefore(d,h);f=w;d=n+1|0;continue}else C=2;else C=2;else C=2;if(2===C){n=R[0];h=m(k,0);B[0]=h;f=[h,w];e=[n,v];continue}}else q=1;else q=1;break;case 4:e=[l[1],g[1]];continue}1===q&&(e=g[1],h?(d=h[0],4===d.tag?ca(m(d[0],a),b,c,n,
[l,0],[d[1],0]):(l=t(c,n),d=ia(a,d),b.insertBefore(d,l),b.removeChild(l)),f=h[1],d=n+1|0):(n=t(c,n),b.removeChild(n),f=0))}else if(h)e=ia(a,h[0]),b.appendChild(e),f=h[1],e=0,d=n+1|0;else return 0}}function Db(a,b){return[[function(c){return m(b[0][0],m(a,c))}]]}function P(a,b){if("number"===typeof b)return 0;switch(b.tag|0){case 1:return aa(function(b,d){return P(a,d)},0,b[0]);case 0:case 2:return m(b[0],a)}}function Pa(a,b){return g(0,[function(c){return P(Db(a,c),b)}])}function ja(a,b,c,d){return g(2,
["","div",a?a[0]:"",b?b[0]:"",c,d])}function ka(a,b,c,d){return g(2,["","p",a?a[0]:"",b?b[0]:"",c,d])}function Qa(a,b,c,d){return g(2,["","input",a?a[0]:"",b?b[0]:"",c,d])}function Eb(a,b){return zb("input",a?a[0]:"",function(a){a=a.target;return void 0!==a?(a=a.value,void 0!==a?m(b,a):0):0})}function Fb(a,b){return Eb([a?a[0]:""],function(a){return[m(b,a)]})}function W(a){if(void 0===a)var b=0;else 248===a.tag?b=1:(b=a[0],b=void 0!==b?+(248===b.tag):0);return b?a:[Gb,a]}function Ra(a){a=a[7].split("/");
var b=a.length;if(2!==b)return 3!==b?1:"#"===a[0]?"Record"===a[1]?[a[2]]:1:1;if("#"===a[0])switch(a[1]){case "":case "Search":return 1;default:return 1}else return 1}function va(a,b){var c=b.length;if(c){for(var d=m(a,b[0]),e=Array(c),f=0,h=c-1|0;f<=h;++f)e[f]=d;d=1;for(c=c-1|0;d<=c;++d)e[d]=m(a,b[d]);return e}return[]}function wa(a){for(var b=a.length-1|0,c=0;;){if(0>b)return c;c=[a[b],c];b=b-1|0}}function Sa(a,b,c){for(var d=b.length-1|0;0<=d;--d)c=A(a,b[d],c);return c}function u(a,b){return b.tag?
b:a}function G(a,b,c,d){var e=a?a[4]:0,f=d?d[4]:0;return[a,b,c,d,e>=f?e+1|0:f+1|0]}function xa(a,b){return[0,a,b,0,1]}function L(a,b,c,d){var e=a?a[4]:0,f=d?d[4]:0;if(e>(f+2|0)){if(a){e=a[3];f=a[2];var h=a[1];a=a[0];if((a?a[4]:0)>=(e?e[4]:0))return G(a,h,f,G(e,b,c,d));if(e)return G(G(a,h,f,e[0]),e[1],e[2],G(e[3],b,c,d))}throw[F,"Map.bal"];}if(f>(e+2|0)){if(d){e=d[3];f=d[2];h=d[1];d=d[0];if((e?e[4]:0)>=(d?d[4]:0))return G(G(a,b,c,d),h,f,e);if(d)return G(G(a,b,c,d[0]),d[1],d[2],G(d[3],h,f,e))}throw[F,
"Map.bal"];}return[a,b,c,d,e>=f?e+1|0:f+1|0]}function la(a,b,c){if(c){var d=c[3],e=c[2],f=c[1],h=c[0],g=N(a,f);return g?0>g?L(la(a,b,h),f,e,d):L(h,f,e,la(a,b,d)):[h,a,b,d,c[4]]}return[0,a,b,0,1]}function ma(a){for(;;)if(a){var b=a[0];if(b)a=b;else return[a[1],a[2]]}else throw na;}function ya(a){if(a){var b=a[0];return b?L(ya(b),a[1],a[2],a[3]):a[3]}throw[F,"Map.remove_min_elt"];}function za(a,b){if(b){var c=b[3],d=b[2],e=b[1];b=b[0];var f=N(a,e);return f?0>f?L(za(a,b),e,d,c):L(b,e,d,za(a,c)):b?c?
(a=ma(c),L(b,a[0],a[1],ya(c))):b:c}return 0}function Ta(a,b){for(;;)if(b)Ta(a,b[0]),A(a,b[1],b[2]),b=b[3];else return 0}function Aa(a,b){if(b){var c=Aa(a,b[0]),d=m(a,b[2]);a=Aa(a,b[3]);return[c,b[1],d,a,b[4]]}return 0}function Ba(a,b){if(b){var c=b[1],d=Ba(a,b[0]),e=A(a,c,b[2]);a=Ba(a,b[3]);return[d,c,e,a,b[4]]}return 0}function Ua(a,b,c){for(;;)if(b)c=Y(a,b[1],b[2],Ua(a,b[0],c)),b=b[3];else return c}function Va(a,b){for(;;)if(b)if(A(a,b[1],b[2]))if(Va(a,b[0]))b=b[3];else return 0;else return 0;else return 1}
function Wa(a,b){for(;;)if(b){if(A(a,b[1],b[2])||Wa(a,b[0]))return 1;b=b[3]}else return 0}function Xa(a,b,c){return c?L(Xa(a,b,c[0]),c[1],c[2],c[3]):xa(a,b)}function Ya(a,b,c){return c?L(c[0],c[1],c[2],Ya(a,b,c[3])):xa(a,b)}function M(a,b,c,d){if(a){if(d){var e=d[4],f=a[4];return f>(e+2|0)?L(a[0],a[1],a[2],M(a[3],b,c,d)):e>(f+2|0)?L(M(a,b,c,d[0]),d[1],d[2],d[3]):G(a,b,c,d)}return Ya(b,c,a)}return Xa(b,c,d)}function da(a,b){if(a){if(b){var c=ma(b);return M(a,c[0],c[1],ya(b))}return a}return b}function ea(a,
b){if(b){var c=b[3],d=b[2],e=b[1];b=b[0];var f=N(a,e);if(f){if(0>f)return a=ea(a,b),[a[0],a[1],M(a[2],e,d,c)];c=ea(a,c);return[M(b,e,d,c[0]),c[1],c[2]]}return[b,[d],c]}return[0,0,0]}function fa(a,b,c){if(b){var d=b[1];if(b[4]>=(c?c[4]:0)){var e=ea(d,c);c=fa(a,b[0],e[0]);var f=Y(a,d,[b[2]],e[1]);a=fa(a,b[3],e[2]);return f?M(c,d,f[0],a):da(c,a)}d=1}else if(c)d=1;else return 0;if(1===d){if(c)return d=c[1],e=ea(d,b),b=fa(a,e[0],c[0]),f=Y(a,d,e[1],[c[2]]),a=fa(a,e[2],c[3]),f?M(b,d,f[0],a):da(b,a);throw[Za,
["map.ml",270,10]];}}function Ca(a,b){if(b){var c=b[2],d=b[1],e=Ca(a,b[0]),f=A(a,d,c);a=Ca(a,b[3]);return f?M(e,d,c,a):da(e,a)}return 0}function Da(a,b){if(b){var c=b[2],d=b[1],e=Da(a,b[0]),f=e[1];e=e[0];var h=A(a,d,c);b=Da(a,b[3]);a=b[1];b=b[0];return h?[M(e,d,c,b),da(f,a)]:[da(e,b),M(f,d,c,a)]}return[0,0]}function Q(a,b){for(;;)if(a)b=[a[1],a[2],a[3],b],a=a[0];else return b}function Ea(a){return a?(Ea(a[0])+1|0)+Ea(a[3])|0:0}function $a(a,b){for(;;){var c=b;if(c)b=c[0],a=[[c[1],c[2]],$a(a,c[3])];
else return a}}function ab(a){return[function(b){b=H(b);return"number"===typeof b?2<=b?g(0,[a]):g(1,["Non-null value"]):g(1,["Non-null value"])}]}function bb(a,b){var c=b[0];return[function(b){b=H(b);return"number"===typeof b?g(1,["Non-fieldable value"]):2===b.tag?(b=b[0][a],void 0!==b?(b=m(c,b),b.tag?g(1,["field `"+(a+("` -> "+b[0]))]):b):g(1,["Field Value is undefined: "+a])):g(1,["Non-fieldable value"])}]}function cb(a){return[function(b){var c=function(a,b){for(;;)if(b){var d=b[1];try{var e=m(b[0][0],
a);return e.tag?c(a,d):e}catch(r){b=d}}else return g(1,["No one-of's matched"])};return c(b,a)}]}function db(a,b){var c=b[0];return[function(b){b=m(c,b);return b.tag?g(1,["map "+b[0]]):g(0,[m(a,b[0])])}]}function eb(a,b){var c=b[0];return[function(b){var d=m(c,b);if(d.tag)return d;d=m(a,d[0]);return m(d[0],b)}]}function fb(a,b){try{return m(a[0],b)}catch(c){return a=W(c),a[0]===E?g(1,[a[1]]):g(1,["Unknown JSON parsing error"])}}function Hb(a){a=a.getAllResponseHeaders();return null!==a?""===a?g(1,
[1]):g(0,[a]):g(1,[0])}function Ib(a){a=Hb(a);return a.tag?a:g(0,[O(function(a){if(2!==a.length)throw[x,"Cannot happen, already checked length"];return[a[0],a[1]]},Jb(function(a){return+(2===a.length)})(wa(va(function(a){return a.split(": ",2)},a[0].split("\r\n")))))])}function Kb(a){var b=function(a,b,c,d){var e=a?a[4]:0,f=d?d[4]:0;return[a,b,c,d,e>=f?e+1|0:f+1|0]},c=function(a,c,d,g){var e=a?a[4]:0,f=g?g[4]:0;if(e>(f+2|0)){if(a){e=a[3];f=a[2];var h=a[1];a=a[0];if((a?a[4]:0)>=(e?e[4]:0))return b(a,
h,f,b(e,c,d,g));if(e)return b(b(a,h,f,e[0]),e[1],e[2],b(e[3],c,d,g))}throw[F,"Map.bal"];}if(f>(e+2|0)){if(g){e=g[3];f=g[2];h=g[1];g=g[0];if((e?e[4]:0)>=(g?g[4]:0))return b(b(a,c,d,g),h,f,e);if(g)return b(b(a,c,d,g[0]),g[1],g[2],b(g[3],h,f,e))}throw[F,"Map.bal"];}return[a,c,d,g,e>=f?e+1|0:f+1|0]},d=function(a,b,g){if(g){var e=g[3],f=g[2],h=g[1],m=g[0],k=N(a,h);return k?0>k?c(d(a,b,m),h,f,e):c(m,h,f,d(a,b,e)):[m,a,b,e,g[4]]}return[0,a,b,0,1]};a=Ib(a);return a.tag?a:g(0,[aa(function(a,b){return d(b[0],
b[1],a)},0,a[0])])}function Lb(a,b){if("number"===typeof a)return a?b.send(null):b.send();switch(a.tag|0){case 0:return b.send(a[0]);case 1:return b.send(a[0]);case 2:return a=aa(function(a,b){a.append(b[0],b[1]);return a},new FormData,a[0]),b.send(a);case 3:return b.send(a[0])}}function Mb(a,b){if("number"===typeof a)switch(a){case 0:return b.responseType="";case 1:return b.responseType="arraybuffer";case 2:return b.responseType="blob";case 3:return b.responseType="document";case 4:return b.responseType=
"json";case 5:return b.responseType="text"}else return b.responseType=a[0]}function Nb(a){a=a.responseType;switch(a){case "":return 0;case "arraybuffer":return 1;case "blob":return 2;case "document":return 3;case "json":return 4;case "text":return 5;default:return[a]}}function Ob(a){var b=a.response;if(null!==b)if(a=Nb(a),"number"===typeof a)switch(a){case 0:return g(0,[b]);case 1:return g(1,[b]);case 2:return g(2,[b]);case 3:return g(3,[b]);case 4:return g(4,[b]);case 5:return g(5,[b])}else return g(6,
[a[0],b]);else return 0}function Pb(a,b){var c=b[1];b=b[0];var d=b[4],e=d[1],f=d[0],h=b[6],r=b[5],n=b[3],l=b[2],k=b[1],p=b[0];return g(2,[function(b){var d=function(c,d){return m(b[0][0],m(a,c))},q=new XMLHttpRequest;if(c){var C=c[0],v=function(a,c){return c?m(a,m(c[0],b)):0};v(function(a){return q.onreadystatechange=a},C[0]);v(function(a){return q.onprogress=a},C[1])}var D=g(1,[1]);q.onerror=function(a){return d(D,a)};var R=g(1,[0]);q.ontimeout=function(a){return d(R,a)};var w=g(1,[2]);q.onabort=
function(a){return d(w,a)};q.onload=function(){var a=Kb(q);var b=a.tag?0:a[0];var c=q.responseURL;a=[q.status,q.statusText];var f=Ob(q);b=[c,a,b,f];if(200>a[0]||300<=a[0])return a=g(1,[g(1,[b])]),d(a,0);a=m(e,b);if(a.tag)return a=g(1,[g(2,[a[0],b])]),d(a,0);a=g(0,[a[0]]);return d(a,0)};try{q.open(p,l,1,"","")}catch(K){C=g(1,[g(0,[l])]),d(C,0)}U(function(a){return q.setRequestHeader(a[0],a[1])},k);Mb(f,q);r&&(q.timeout=r[0]);q.withCredentials=h;Lb(n,q);return 0}])}function Qb(a){return g(1,[a])}function Rb(a){var b=
I[17](function(a,b){return[a,b]},I[11]("id",I[2]),I[11]("title",I[2]));b=I[17](function(a,b){return[b,a]},I[11]("resultCount",I[3]),I[11]("records",I[8](b)));a=I[32](b,a);return a.tag?2:[a[0]]}function Sb(a){var b=a[1];if("number"===typeof b)switch(b){case 0:var c="not asked";break;case 1:c="loading";break;case 2:c="error"}else c=b[0],b=""+c[1],c=va(function(a){return a[1]},c[0]),c="ResultCnt: "+(b+(", records: "+J("<br>",wa(c))));return ja(0,0,0,[ka(0,0,0,[g(1,[a[0]]),0]),[Qa(0,0,[g(0,["type","text"]),
[g(0,["name","lookfor"]),[g(0,["value",a[0]]),[Fb(0,function(a){return g(0,[a])}),0]]]],0),[Qa(0,0,[g(0,["type","submit"]),[g(3,["click",g(1,[0]),[0]]),[g(0,["value","Search!"]),0]]],0),[ka(0,0,0,[g(1,[c]),0]),0]]]])}function Tb(){(function(){"remove"in Element.prototype||(Element.prototype.remove=function(){this.parentNode&&this.parentNode.removeChild(this)})})();(function(){for(var a=0,b=["ms","moz","webkit","o"],c=0;c<b.length&&!window.requestAnimationFrame;++c)window.requestAnimationFrame=window[b[c]+
"RequestAnimationFrame"],window.cancelAnimationFrame=window[b[c]+"CancelAnimationFrame"]||window[b[c]+"CancelRequestAnimationFrame"];window.requestAnimationFrame||(window.requestAnimationFrame=function(b,c){var d=(new Date).getTime(),e=Math.max(0,16-(d-a));c=window.setTimeout(function(){b(d+e)},e);a=d+e;return c});window.cancelAnimationFrame||(window.cancelAnimationFrame=function(a){clearTimeout(a)})})();return 0}function Ub(a,b){return g(1,[a,function(a){return m(b,a[0])},[0]])}function X(a,b,c,
d){var e=function(a,b){for(;;){var c=b,d=a;if("number"===typeof c)return 0;switch(c.tag|0){case 0:return(b=c[0])?U(function(a){return function(b){return e(a,b)}}(d),b):0;case 1:return c[2][0]=[m(c[1],d)],0;case 2:d=m(c[0],d),b=c[1],a=d}}},f=function(a,b){for(;;){var c=b,d=a;if("number"===typeof c)return 0;switch(c.tag|0){case 0:return(b=c[0])?U(function(a){return function(b){return f(a,b)}}(d),b):0;case 1:return b=c[2],(c=b[0])?(b[0]=0,m(c[0],0)):0;case 2:d=m(c[0],d),b=c[1],a=d}}},g=0;if("number"===
typeof c){if("number"===typeof d)return d;g=1}else switch(c.tag|0){case 0:if("number"===typeof d)g=1;else if(d.tag)g=1;else return function(c,d){for(;;){var g=c;if(g)c=g[1],g=g[0],d?(X(a,b,g,d[0]),d=d[1]):(f(a,g),d=0);else if(d)e(b,d[0]),d=d[1],c=0;else return 0}}(c[0],d[0]),d;break;case 1:if("number"!==typeof d&&1===d.tag&&c[0]===d[0])return d[2][0]=c[2][0],d;g=1;break;case 2:if("number"!==typeof d&&2===d.tag){g=m(c[0],a);var r=m(d[0],b);X(g,r,c[1],d[1]);return d}g=1}if(1===g)return f(a,c),e(b,d),
d}function Vb(a,b,c){var d=[a],e=[[function(){console.log("INVALID enqueue CALL!");return 0}]],f=m(b,e),g=[0],r=function(a){var b=g[0];if(b)return g[0]=[[a,b[0]]],0;g[0]=[0];a=A(f[2],d[0],a);d[0]=a;if(a=g[0])return(a=a[0])?(g[0]=0,U(r,Ha(a,0))):g[0]=0;throw[x,"INVALID message queue state, should never be None during message processing!"];};e[0]=[r];m(f[0],0);return{pushMsg:r,shutdown:function(){e[0]=[function(){console.log("INVALID message enqueued when shut down");return 0}];var a=m(c,d[0]);m(f[3],
a);return 0},getHtmlString:function(){return m(f[1],d[0])}}}function Wb(a,b,c,d,e,f){if(f){var g=f[0];return function(f){var h=[0],l=[d],k=[0],r=function(){if(k[0]){var a=[m(b,l[0]),0];ca(f,g,g.childNodes,0,h[0],a);h[0]=a;k[0]=0}return 0},p=function(){for(;0<g.childNodes.length;){var a=g.firstChild;null!==a&&g.removeChild(a)}return 0},z=[0],u=function(a){a=m(c,a);z[0]=X(f,f,z[0],a);return 0};return[function(){p(0);P(f,e);u(l[0]);k[0]=[-1];r(16);return 0},function(a){return ra(m(b,a))},function(b,
c){b=A(a,b,c);c=b[0];l[0]=c;P(f,b[1]);k[0]||(k[0]=[-1],r(16));u(c);return c},function(a){k[0]=0;P(f,a);z[0]=X(f,f,z[0],0);h[0]=0;p(0);return 0}]}}return function(f){var g=[0],h=function(a){a=m(c,a);g[0]=X(f,f,g[0],a);return 0};return[function(){P(f,e);h(d);return 0},function(a){return ra(m(b,a))},function(b,c){b=A(a,b,c);c=b[0];P(f,b[1]);h(c);return c},function(a){P(f,a);g[0]=X(f,f,g[0],0);return 0}]}}function gb(a){return[a.href,a.protocol,a.host,a.hostname,a.port,a.pathname,a.search,a.hash,a.username,
a.password,a.origin]}function Xb(a){return Ub("navigation",function(b){hb[0]=[function(c){return m(b[0],m(a,c))}];var c=function(){var a=hb[0];if(a){var b=gb(document.location);m(a[0],b)}return 0};window.addEventListener("popstate",c,0);return function(){return window.removeEventListener("popstate",c,0)}})}function ib(a){return g(0,[a])}function Fa(a){return g(1,[a])}function Ga(a){return g(2,[a])}function jb(a,b){return[[Ra(b),Yb,Zb],0]}function kb(){return 0}function lb(a,b){switch(b.tag|0){case 0:return[[Ra(b[0]),
a[1],a[2]],0];case 1:var c=a[1];b=b[0];"number"===typeof b?(b=[c[0],1,c[2]],c=Pb(Qb,[["GET",0,"https://api.finna.fi/api/v1/search?lookfor="+(c[0]+"&field[]=id&field[]=title&prettyPrint=true&limit=5"),0,$b,0,0],0]),c=[b,c]):b.tag?(b=b[0],c=b.tag?[[c[0],2,c[2]],0]:[[c[0],Rb(b[0]),c[2]],0]):c=[[b[0],c[1],c[2]],0];return[[a[0],c[0],a[2]],Pa(Fa,c[1])];case 2:return c=[a[2],0],[[a[0],a[1],c[0]],Pa(Ga,c[1])];case 3:return[[b[0],a[1],a[2]],0]}}function mb(a){if("number"===typeof a[0]){var b=g(3,[0]);b=[g(3,
["click",g(1,[b]),[0]]),0];var c=[g(1,["main"]),0];b=g(2,["","a","","",b,c]);a=ja(0,0,0,[b,[nb(Fa,Sb(a[1])),0]])}else a=nb(Ga,ja(0,0,0,[ka(0,0,0,[g(1,["rec"]),0]),0]));return ja(0,0,0,[ka(0,0,0,[a,0]),0])}var x=["Failure",-2],F=["Invalid_argument",-3],na=["Not_found",-6],ua=["Match_failure",-7],Za=["Assert_failure",-10];x.tag=248;F.tag=248;na.tag=248;ua.tag=248;Za.tag=248;var xb=Math.imul||function(a,b){b|=0;return((a>>16)*b<<16)+(a&65535)*b|0},qa=[0];Z("Pervasives.Exit");var Jb=function(a){return function(b){for(var c=
0,d=b;;){var e=d;b=c;if(e)d=e[1],e=e[0],m(a,e)&&(c=[e,b]);else return Ha(b,0)}}};g(0,[""]);var Zb=[0],Gb=Z("Js_exn.Error");Z("CamlinternalFormat.Type_mismatch");Z("Array.Bottom");var H=function(a){var b=typeof a;return"string"===b?g(0,[a]):"number"===b?g(1,[a]):"boolean"===b?!0===a?1:0:null===a?2:Array.isArray(a)?g(3,[a]):g(2,[a])},ac=[0,function(a){return a?0:1},function(a,b){for(;;)if(b){var c=N(a,b[1]);if(c)b=0>c?b[0]:b[3];else return 1}else return 0},la,xa,za,fa,function(a,b,c){b=Q(b,0);for(c=
Q(c,0);;)if(b)if(c){var d=N(b[0],c[0]);if(0!==d)return d;d=A(a,b[1],c[1]);if(0!==d)return d;c=Q(c[2],c[3]);b=Q(b[2],b[3])}else return 1;else return c?-1:0},function(a,b,c){b=Q(b,0);for(c=Q(c,0);;)if(b)if(c)if(!N(b[0],c[0])&&A(a,b[1],c[1]))c=Q(c[2],c[3]),b=Q(b[2],b[3]);else return 0;else return 0;else return c?0:1},Ta,Ua,Va,Wa,Ca,Da,Ea,function(a){return $a(0,a)},ma,function(a){for(;;)if(a){var b=a[3];if(b)a=b;else return[a[1],a[2]]}else throw na;},ma,ea,function(a,b){for(;;)if(b){var c=N(a,b[1]);
if(c)b=0>c?b[0]:b[3];else return b[2]}else throw na;},Aa,Ba],E=Z("Tea_json.Decoder.ParseFail"),I=[ac,E,[function(a){a=H(a);return"number"===typeof a?g(1,["Non-string value"]):a.tag?g(1,["Non-string value"]):g(0,[a[0]])}],[function(a){a=H(a);return"number"===typeof a?g(1,["Non-int value"]):1===a.tag?(a=a[0],-2147483648<a&&2147483647>a?g(0,[a|0]):g(1,["number out of int range"])):g(1,["Non-int value"])}],[function(a){a=H(a);return"number"===typeof a?g(1,["Non-float-value"]):1===a.tag?g(0,[a[0]]):g(1,
["Non-float-value"])}],[function(a){a=H(a);if("number"===typeof a)switch(a){case 0:return g(0,[0]);case 1:return g(0,[1]);case 2:return g(1,["Non-boolean value"])}else return g(1,["Non-boolean value"])}],ab,function(a){var b=a[0];return[function(a){a=H(a);if("number"!==typeof a&&3===a.tag){var c=function(a){a=m(b,a);if(a.tag)throw[E,a[0]];return a[0]};try{return g(0,[O(c,wa(a[0]))])}catch(e){a=W(e);if(a[0]===E)return g(1,["list -> "+a[1]]);throw a;}}else return g(1,["Non-list value"])}]},function(a){var b=
a[0];return[function(a){a=H(a);if("number"!==typeof a&&3===a.tag){var c=function(a){a=m(b,a);if(a.tag)throw[E,a[0]];return a[0]};try{return g(0,[va(c,a[0])])}catch(e){a=W(e);if(a[0]===E)return g(1,["array -> "+a[1]]);throw a;}}else return g(1,["Non-array value"])}]},function(a){var b=a[0];return[function(a){a=H(a);if("number"!==typeof a&&2===a.tag){var c=a[0];a=Object.keys(c);var e=function(a,d){var e=c[a];if(void 0!==e){e=m(b,e);if(e.tag)throw[E,e[0]];return[[a,e[0]],d]}throw[E,"Key is undefined: "+
a];};try{return g(0,[Sa(e,a,0)])}catch(f){a=W(f);if(a[0]===E)return g(1,["Invalid keyValuePair parsing: "+a[1]]);throw a;}}else return g(1,["Non-keyValuePair value"])}]},function(a){var b=a[0];return[function(a){a=H(a);if("number"!==typeof a&&2===a.tag){var c=a[0];a=Object.keys(c);var e=function(a,d){var e=c[a];if(void 0!==e){e=m(b,e);if(e.tag)throw[E,e[0]];return la(a,e[0],d)}throw[E,"Key is undefined: "+a];};try{return g(0,[Sa(e,a,0)])}catch(f){a=W(f);if(a[0]===E)return g(1,["Invalid dict parsing: "+
a[1]]);throw a;}}else return g(1,["Non-dict value"])}]},bb,function(a,b){return Ia(bb,a,b)},function(a,b){var c=b[0];return[function(b){b=H(b);return"number"===typeof b?g(1,["Non-array value"]):3===b.tag?(b=b[0],0>a||a>b.length?g(1,["Array index out of range: "+a]):m(c,t(b,a))):g(1,["Non-array value"])}]},function(a){var b=a[0];return[function(a){a=m(b,a);return a.tag?g(0,[0]):g(0,[[a[0]]])}]},cb,db,function(a,b,c){var d=c[0],e=b[0];return[function(b){var c=m(e,b);b=m(d,b);if(c.tag)var f=1;else if(b.tag)f=
1;else return g(0,[A(a,c[0],b[0])]);if(1===f){c=b.tag?[b[0]]:c.tag?[c[0]]:0;if(c)return g(1,["map2 -> "+c[0]]);throw[x,"Impossible case"];}}]},function(a,b,c,d){var e=d[0],f=c[0],h=b[0];return[function(b){var c=m(h,b),d=m(f,b);b=m(e,b);if(c.tag)var k=1;else if(d.tag)k=1;else if(b.tag)k=1;else return g(0,[Y(a,c[0],d[0],b[0])]);if(1===k){c=u(b,u(d,c));if(c.tag)return g(1,["map3 -> "+c[0]]);throw[x,"Impossible case"];}}]},function(a,b,c,d,e){var f=e[0],h=d[0],k=c[0],n=b[0];return[function(b){var c=m(n,
b),d=m(k,b),e=m(h,b);b=m(f,b);if(c.tag)var l=1;else if(d.tag)l=1;else if(e.tag)l=1;else if(b.tag)l=1;else return c=c[0],d=d[0],e=e[0],b=b[0],l=a.length,e=4===l?a(c,d,e,b):rb(a,c,d,e,b,l),g(0,[e]);if(1===l){e=u(b,u(e,u(d,c)));if(e.tag)return g(1,["map4 -> "+e[0]]);throw[x,"Impossible case"];}}]},function(a,b,c,d,e,f){var h=f[0],k=e[0],n=d[0],l=c[0],p=b[0];return[function(b){var c=m(p,b),d=m(l,b),e=m(n,b),f=m(k,b);b=m(h,b);if(c.tag)var v=1;else if(d.tag)v=1;else if(e.tag)v=1;else if(f.tag)v=1;else if(b.tag)v=
1;else return c=c[0],d=d[0],e=e[0],f=f[0],b=b[0],v=a.length,f=5===v?a(c,d,e,f,b):sb(a,c,d,e,f,b,v),g(0,[f]);if(1===v){f=u(b,u(f,u(e,u(d,c))));if(f.tag)return g(1,["map5 -> "+f[0]]);throw[x,"Impossible case"];}}]},function(a,b,c,d,e,f,h){var k=h[0],n=f[0],l=e[0],p=d[0],t=c[0],w=b[0];return[function(b){var c=m(w,b),d=m(t,b),e=m(p,b),f=m(l,b),h=m(n,b);b=m(k,b);if(c.tag)var r=1;else if(d.tag)r=1;else if(e.tag)r=1;else if(f.tag)r=1;else if(h.tag)r=1;else if(b.tag)r=1;else return c=c[0],d=d[0],e=e[0],f=
f[0],h=h[0],b=b[0],r=a.length,h=6===r?a(c,d,e,f,h,b):tb(a,c,d,e,f,h,b,r),g(0,[h]);if(1===r){h=u(b,u(h,u(f,u(e,u(d,c)))));if(h.tag)return g(1,["map6 -> "+h[0]]);throw[x,"Impossible case"];}}]},function(a,b,c,d,e,f,h,k){var n=k[0],l=h[0],r=f[0],t=e[0],w=d[0],y=c[0],A=b[0];return[function(b){var c=m(A,b),d=m(y,b),e=m(w,b),f=m(t,b),h=m(r,b),k=m(l,b);b=m(n,b);if(c.tag)var q=1;else if(d.tag)q=1;else if(e.tag)q=1;else if(f.tag)q=1;else if(h.tag)q=1;else if(k.tag)q=1;else if(b.tag)q=1;else{c=c[0];d=d[0];
e=e[0];f=f[0];h=h[0];k=k[0];b=b[0];q=a.length;if(7===q)c=a(c,d,e,f,h,k,b);else b:{var B=0;if(7<q||0>q)c=p(a,[c,d,e,f,h,k,b]);else{switch(q){case 0:case 1:B=1;break;case 2:c=p(a(c,d),[e,f,h,k,b]);break b;case 3:c=p(a(c,d,e),[f,h,k,b]);break b;case 4:c=p(a(c,d,e,f),[h,k,b]);break b;case 5:c=p(a(c,d,e,f,h),[k,b]);break b;case 6:c=p(a(c,d,e,f,h,k),[b]);break b;case 7:c=a(c,d,e,f,h,k,b);break b}c=1===B?p(a(c),[d,e,f,h,k,b]):void 0}}return g(0,[c])}if(1===q){c=u(b,u(k,u(h,u(f,u(e,u(d,c))))));if(c.tag)return g(1,
["map7 -> "+c[0]]);throw[x,"Impossible case"];}}]},function(a,b,c,d,e,f,h,k,n){var l=n[0],r=k[0],t=h[0],w=f[0],y=e[0],A=d[0],C=c[0],v=b[0];return[function(b){var c=m(v,b),d=m(C,b),e=m(A,b),f=m(y,b),h=m(w,b),k=m(t,b),n=m(r,b);b=m(l,b);if(c.tag)var q=1;else if(d.tag)q=1;else if(e.tag)q=1;else if(f.tag)q=1;else if(h.tag)q=1;else if(k.tag)q=1;else if(n.tag)q=1;else if(b.tag)q=1;else{c=c[0];d=d[0];e=e[0];f=f[0];h=h[0];k=k[0];n=n[0];b=b[0];q=a.length;if(8===q)c=a(c,d,e,f,h,k,n,b);else b:{var z=0;if(7<q||
0>q)c=p(a,[c,d,e,f,h,k,n,b]);else{switch(q){case 0:case 1:z=1;break;case 2:c=p(a(c,d),[e,f,h,k,n,b]);break b;case 3:c=p(a(c,d,e),[f,h,k,n,b]);break b;case 4:c=p(a(c,d,e,f),[h,k,n,b]);break b;case 5:c=p(a(c,d,e,f,h),[k,n,b]);break b;case 6:c=p(a(c,d,e,f,h,k),[n,b]);break b;case 7:c=p(a(c,d,e,f,h,k,n),[b]);break b}c=1===z?p(a(c),[d,e,f,h,k,n,b]):void 0}}return g(0,[c])}if(1===q){c=u(b,u(n,u(k,u(h,u(f,u(e,u(d,c)))))));if(c.tag)return g(1,["map8 -> "+c[0]]);throw[x,"Impossible case"];}}]},function(a){return[function(){return g(0,
[a])}]},function(a){return[function(){return g(1,[a])}]},[function(a){return g(0,[a])}],eb,function(a){return eb(a,[function(){return g(0,[0])}])},function(a){return cb([ab(0),[db(function(a){return[a]},a),0]])},fb,function(a,b){try{return m(a[0],b)}catch(c){return a=W(c),a[0]===E?g(1,[a[1]]):g(1,["Unknown JSON parsing error"])}},function(a,b){try{var c=JSON.parse(b);return fb(a,c)}catch(d){return g(1,["Invalid JSON string"])}}],$b=function(a){return[5,function(b){b=b[3];return"number"===typeof b?
g(1,["Non-text response returned"]):5===b.tag?m(a,b[0]):g(1,["Non-text response returned"])}]}(function(a){return g(0,[a])}),Yb=["start",0,0],nb=function(a,b){return g(4,[function(b){return[[function(c){return m(b[0][0],m(a,c))}]]},b])},hb=[0],bc=function(a,b){var c=[function(a){return A(b[0],a,gb(document.location))},b[1],b[2],function(c){return g(0,[[Xb(a),[m(b[3],c),0]]])},b[4]];return function(a,b){Tb(0);var d=m(c[0],b);b=d[0];a=Wb(c[1],c[2],c[3],b,d[1],null==a?0:[a]);return Vb(b,a,c[4])}}(ib,
[jb,lb,mb,kb,function(){return 0}]);k.urlChanged=ib;k.searchMsg=Fa;k.recordMsg=Ga;k.openRoute=function(a){return g(3,[a])};k.init=jb;k.subscriptions=kb;k.update=lb;k.view=mb;k.main=bc;return k}({});
